version: 2
jobs:
  build:
    docker:
      - image: circleci/node-alpine
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      - run:
          name: install packages
          command: npm install
      - run:
          name: jest tests
          command npm run test