version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.11.2
    steps:
      - checkout
      - run:
        name: install packages
        command: npm install
      - run:
        name: test
        command: npm test